# Generated by Django 5.0.7 on 2024-12-31 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects_Details',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('project_created_at', models.DateTimeField(auto_now=True)),
                ('project_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Members',
            fields=[
                ('prmember_id', models.AutoField(primary_key=True, serialize=False)),
                ('prmember_role', models.CharField(choices=[('Admin', 'Admin'), ('Member', 'Member')], max_length=50)),
                ('prmember_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
                ('prmember_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects_details')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.TextField()),
                ('task_status', models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Done', 'Done')], max_length=50)),
                ('task_priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
                ('task_created_at', models.DateTimeField(auto_now=True)),
                ('task_due_date', models.DateTimeField(auto_now=True)),
                ('task_assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
                ('task_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects_details')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comments_id', models.AutoField(primary_key=True, serialize=False)),
                ('comments_content', models.TextField()),
                ('comments_created_at', models.DateTimeField(auto_now=True)),
                ('comments_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
                ('comments_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tasks')),
            ],
        ),
    ]
